### ISSUE TITLE
Bug from version 3.2.0

### ISSUE THREAD

**Issue by WisdomPill** [django/asgiref#114]
I'm using channels in my application, when I updated asgiref I started having tests that fail, especially one where I have a websocket that sends updates after a model gets updated using a receiver on the post_save signal of a model using the async_to_sync method. The issue is with a serializer that generates a field using a SerializeMethodField, but this does not matter since the serializer is tested in many other methods and those tests all pass. The odd thing is that the traceback has a asgiref call, so I tried all the versions in the middle of the update, (I was going from 3.1.2 to 3.2.1), I discovered that the version that breaks things is 3.2.0, I updated all the other packages related to channels and the tests pass.

This is the traceback that got me thinking something was wrong with asgiref.
It says that that there are other 1 connections to the database.

``` python
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ObjectInUse: database "test_timing_services" is being accessed by other users
DETAIL:  There is 1 other session using the database.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 168, in <module>
    utility.execute()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 142, in execute
    _create_command().run_from_argv(self.argv)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 104, in handle
    failures = TestRunner(test_labels, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_runner.py", line 255, in run_tests
    extra_tests=extra_tests, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/runner.py", line 639, in run_tests
    self.teardown_databases(old_config)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/runner.py", line 583, in teardown_databases
    keepdb=self.keepdb,
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/utils.py", line 299, in teardown_databases
    connection.creation.destroy_test_db(old_name, verbosity, keepdb)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 259, in destroy_test_db
    self._destroy_test_db(test_database_name, verbosity)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 276, in _destroy_test_db
    % self.connection.ops.quote_name(test_database_name))
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: database "test_timing_services" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

I'm sure that there is no other resource accessing the database except for the test runner.
I'm using python 3.7, and the following is the serializer that should be called just once while using the debugger the method of the serializer that fails is called twice, the first it has the cached field needed while the second it doesn't.

This is the stack trace from the async_to_sync call

```
File "/Users/anas/Projects/timing_services/timing/receivers.py", line 17, in lap_post_save
    async_to_sync(update_training_websocket)(instance, layer)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/asgiref/sync.py", line 110, in __call__
    return call_result.result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/asgiref/sync.py", line 142, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Users/anas/Projects/timing_services/timing/ws/v1/utils.py", line 66, in update_training_websocket
    lap_json = LapSerializer(lap).data
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/rest_framework/serializers.py", line 559, in data
    ret = super().data
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/rest_framework/serializers.py", line 261, in data
    self._data = self.to_representation(self.instance)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/rest_framework/serializers.py", line 526, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/rest_framework/fields.py", line 1873, in to_representation
    return method(value)
  File "/Users/anas/Projects/timing_services/timing/api/v1/serializers.py", line 98, in get_tag_possession
    user = obj.round.training.tag.user
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = self.get_object(instance)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 145, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
timing.models.Training.DoesNotExist: Training matching query does not exist.
```

**Comment by andrewgodwin** [comment]
Ah, this is likely related to the new underlying implementation of sync_to_async that got pushed up in that version. Is there any chance you can reduce it to a simpler test case?

**Comment by WisdomPill** [comment]
Doing some other experiments it seems to me that, even if I don't access the db the connection is being destroyed before the end of usage, for instance if in my test I put a breakpoint even if there's no async_to_sync function call the error is still the same, I used a print method just for putting a breakpoint there. Of course I tried the same test using the 3.1.4 version and no error was thrown.

This is the stack trace, by the way.
```python
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ObjectInUse: database "test_timing_services" is being accessed by other users
DETAIL:  There is 1 other session using the database.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 168, in <module>
    utility.execute()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 142, in execute
    _create_command().run_from_argv(self.argv)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py", line 104, in handle
    failures = TestRunner(test_labels, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_runner.py", line 255, in run_tests
    extra_tests=extra_tests, **options)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/django_test_runner.py", line 156, in run_tests
    return super(DjangoTeamcityTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/runner.py", line 639, in run_tests
    self.teardown_databases(old_config)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/runner.py", line 583, in teardown_databases
    keepdb=self.keepdb,
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/test/utils.py", line 299, in teardown_databases
    connection.creation.destroy_test_db(old_name, verbosity, keepdb)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 259, in destroy_test_db
    self._destroy_test_db(test_database_name, verbosity)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 276, in _destroy_test_db
    % self.connection.ops.quote_name(test_database_name))
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/anas/.envs/timing_services/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: database "test_timing_services" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

I tried not using the PyCharm test runner but the result is the same, the versions >=3.2.0 break a few tests, it seems to me that the tests that are broken are the ones that take more time, in those and other cases the connection is not drained properly, and the next time that I run the tests the database is still there. I'm  not if it's because django keeps the database id the test do not pass or what.

**Comment by andrewgodwin** [comment]
Hm, curious. The main change you would have brought in was probably https://github.com/django/asgiref/commit/3a8f32f88f08c481cb3fdd707a409638a7abcf77, which holds open the main thread while some async code is running.

Is it always the same test that breaks every time, or random ones? Can you run just a single test by itself and cause the problem?

**Comment by WisdomPill** [comment]
Always the same, but every test can have the same issue if there's a breakpoint, not if it's too slow, I tried with sleep method and the issue did not happen.

I did some more digging into commits, going up and down the history and I found the guilty commit. The commit is this https://github.com/django/asgiref/commit/85b80b071b946281bf7aa2440151740be51a8938 

I did not dive into the issue, since I'm missing some basic async knowledge, (I've barely used it except from channels websockets and I just read once the documentation).

Hope this helps, just ping me if you need more info, I will try to wrap my head around it anyway.

**Comment by andrewgodwin** [comment]
Hm, there's really not a lot I can do to fix this without being able to replicate it locally. Any way you can get a single test that fails all the time for me so I can try to get it breaking here?

That commit is definitely something that could break, as it's big, but I'm not sure how (and it was, in fact, less buggy than what it replaced according to our own tests). Thus, without being able to get a failure on my end, I can't do anything.

**Comment by andrewgodwin** [comment]
Closing due to inactivity.
