### ISSUE TITLE
set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by Dochomorka** [django/asgiref#156]
hello, everyone
related to #143 
i could not found the solution! sometimes it works sometimes it does not! very confusing.

am using windwos 10, XAMPP 3.2.4, python 3.8.2, Django 3.0.5

Request Method: GET
Request URL: http://localhost/admin/

Django Version: 3.0.5
Python Version: 3.8.2
Installed Applications:
['registration',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\sessions\backends\base.py", line 199, in _get_session
    return self._session_cache

During handling of the above exception ('SessionStore' object has no attribute '_session_cache'), another exception occurred:
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\admin\sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\admin\sites.py", line 220, in inner
    if not self.has_permission(request):
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\admin\sites.py", line 194, in has_permission
    return request.user.is_active and request.user.is_staff
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\utils\functional.py", line 224, in inner
    self._setup()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\utils\functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\__init__.py", line 173, in get_user
    user_id = _get_user_session_key(request)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\__init__.py", line 58, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\sessions\backends\base.py", line 64, in __getitem__
    return self._session[key]
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\sessions\backends\base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\db\models\sql\compiler.py", line 1149, in execute_sql
    cursor = self.connection.cursor()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\django\utils\asyncio.py", line 19, in inner
    event_loop = asyncio.get_event_loop()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\asyncio\events.py", line 636, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "c:\users\hp\appdata\local\programs\python\python38\lib\asyncio\events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "c:\users\hp\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 310, in __init__
    super().__init__(proactor)
  File "c:\users\hp\appdata\local\programs\python\python38\lib\asyncio\proactor_events.py", line 632, in __init__
    signal.set_wakeup_fd(self._csock.fileno())

Exception Type: ValueError at /admin/
Exception Value: set_wakeup_fd only works in main thread

**Comment by Dochomorka** [comment]
downgrading python version to 3.7.7 solves my problem
