### ISSUE TITLE
`NameError: name 'TypeError' is not defined` in Apache (mod_wsgi)

### ISSUE THREAD

**Issue by Leekyungun** [django/asgiref#210]
I linked apache and the error below comes out.
```
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
```

Please refer to the issues below for detailed specifications.
https://github.com/GrahamDumpleton/mod_wsgi/issues/626

I think there is an error here.
https://github.com/django/asgiref/blob/master/asgiref/local.py#L97

When i check Debug(apache loglevel debug), there seems to be problems with all the process dying and coming back to life.
I don't know what to do.

Thank you. I look forward to hearing from you.

```
[Wed Nov 04 11:16:51.849286 2020] [authz_core:debug] [pid 23585:tid 140054311692032] mod_authz_core.c(802): [client 172.16.1.155:64184] AH01626: authorization result of Require all granted: granted
[Wed Nov 04 11:16:51.849320 2020] [authz_core:debug] [pid 23585:tid 140054311692032] mod_authz_core.c(802): [client 172.16.1.155:64184] AH01626: authorization result of <RequireAny>: granted
[Wed Nov 04 11:16:51.849352 2020] [authz_core:debug] [pid 23585:tid 140054311692032] mod_authz_core.c(802): [client 172.16.1.155:64184] AH01626: authorization result of Require all granted: granted
[Wed Nov 04 11:16:51.849357 2020] [authz_core:debug] [pid 23585:tid 140054311692032] mod_authz_core.c(802): [client 172.16.1.155:64184] AH01626: authorization result of <RequireAny>: granted
[Wed Nov 04 20:17:03.783009 2020] [wsgi:info] [pid 23581:tid 140054350087936] mod_wsgi (pid=23581): Daemon process idle inactivity timer expired, stopping process 'api'.
[Wed Nov 04 20:17:03.783094 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Shutdown requested 'api'.
[Wed Nov 04 20:17:03.783668 2020] [wsgi:debug] [pid 23581:tid 140054143903488] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 14 in daemon process 'api'.
[Wed Nov 04 20:17:03.783690 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Stopping process 'api'.
[Wed Nov 04 20:17:03.783698 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Destroying interpreters.
[Wed Nov 04 20:17:03.783706 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Destroy interpreter 'api'.
[Wed Nov 04 20:17:03.783730 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): End interpreter 'api'.
[Wed Nov 04 20:17:03.783841 2020] [wsgi:debug] [pid 23581:tid 140054211045120] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 6 in daemon process 'api'.
[Wed Nov 04 20:17:03.783887 2020] [wsgi:debug] [pid 23581:tid 140054219437824] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 5 in daemon process 'api'.
[Wed Nov 04 20:17:03.783921 2020] [wsgi:debug] [pid 23581:tid 140054227830528] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 4 in daemon process 'api'.
[Wed Nov 04 20:17:03.783956 2020] [wsgi:debug] [pid 23581:tid 140054236223232] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 3 in daemon process 'api'.
[Wed Nov 04 20:17:03.783990 2020] [wsgi:debug] [pid 23581:tid 140054244615936] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 2 in daemon process 'api'.
[Wed Nov 04 20:17:03.784020 2020] [wsgi:debug] [pid 23581:tid 140054253008640] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 1 in daemon process 'api'.
[Wed Nov 04 11:17:03.784697 2020] [authz_core:debug] [pid 23583:tid 140054387226368] mod_authz_core.c(802): [client 172.16.3.114:9768] AH01626: authorization result of Require all granted: granted
[Wed Nov 04 11:17:03.784711 2020] [authz_core:debug] [pid 23583:tid 140054387226368] mod_authz_core.c(802): [client 172.16.3.114:9768] AH01626: authorization result of <RequireAny>: granted
[Wed Nov 04 11:17:03.784799 2020] [authz_core:debug] [pid 23583:tid 140054387226368] mod_authz_core.c(802): [client 172.16.3.114:9768] AH01626: authorization result of Require all granted: granted
[Wed Nov 04 11:17:03.784808 2020] [authz_core:debug] [pid 23583:tid 140054387226368] mod_authz_core.c(802): [client 172.16.3.114:9768] AH01626: authorization result of <RequireAny>: granted
[Wed Nov 04 20:17:03.784948 2020] [wsgi:debug] [pid 23581:tid 140054328780544] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 0 in daemon process 'api'.
[Wed Nov 04 20:17:03.793808 2020] [wsgi:debug] [pid 23581:tid 140054152296192] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 13 in daemon process 'api'.
[Wed Nov 04 20:17:03.793872 2020] [wsgi:debug] [pid 23581:tid 140054160688896] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 12 in daemon process 'api'.
[Wed Nov 04 20:17:03.793902 2020] [wsgi:debug] [pid 23581:tid 140054169081600] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 11 in daemon process 'api'.
[Wed Nov 04 20:17:03.793932 2020] [wsgi:debug] [pid 23581:tid 140054177474304] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 10 in daemon process 'api'.
[Wed Nov 04 20:17:03.793961 2020] [wsgi:debug] [pid 23581:tid 140054185867008] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 9 in daemon process 'api'.
[Wed Nov 04 20:17:03.793990 2020] [wsgi:debug] [pid 23581:tid 140054194259712] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 8 in daemon process 'api'.
[Wed Nov 04 20:17:03.794016 2020] [wsgi:debug] [pid 23581:tid 140054202652416] src/server/mod_wsgi.c(9099): mod_wsgi (pid=23581): Exiting thread 7 in daemon process 'api'.
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f60f58eaa60>
Traceback (most recent call last):
  File "/data/venv/api/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Wed Nov 04 20:17:03.847326 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Cleanup interpreter ''.
[Wed Nov 04 20:17:03.848481 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Terminating Python.
[Wed Nov 04 20:17:03.853612 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Python has shutdown.
[Wed Nov 04 20:17:03.853641 2020] [wsgi:info] [pid 23581:tid 140054670247808] mod_wsgi (pid=23581): Exiting process 'api'.
[Wed Nov 04 11:17:04.346406 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23581): Process 'api' has died, deregister and restart it.
[Wed Nov 04 11:17:04.346442 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23581): Process 'api' terminated normally, exit code 0
[Wed Nov 04 11:17:04.346447 2020] [wsgi:info] [pid 2320:tid 140054670247808] mod_wsgi (pid=23581): Process 'api' has been deregistered and will no longer be monitored.
[Wed Nov 04 11:17:04.346913 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748): Starting process 'api' with uid=1000, gid=1000 and threads=15.
[Wed Nov 04 11:17:04.347334 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748): Python home /data/venv/api.
[Wed Nov 04 11:17:04.347383 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748): Initializing Python.
[Wed Nov 04 11:17:04.364879 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748): Attach interpreter ''.
[Wed Nov 04 11:17:04.380041 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748): Create interpreter 'api'.
[Wed Nov 04 11:17:04.383321 2020] [wsgi:info] [pid 23748:tid 140054670247808] mod_wsgi (pid=23748, process='api', application='api'): Loading Python script file '/data/ONT-invest-api/config/wsgi_development.py'.
[Wed Nov 04 11:17:04.612451 2020] [wsgi:debug] [pid 23748:tid 140054328780544] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 0 in daemon process 'api'.
[Wed Nov 04 11:17:04.612906 2020] [wsgi:debug] [pid 23748:tid 140054253008640] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 1 in daemon process 'api'.
[Wed Nov 04 11:17:04.612999 2020] [wsgi:debug] [pid 23748:tid 140054227830528] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 4 in daemon process 'api'.
[Wed Nov 04 11:17:04.612992 2020] [wsgi:debug] [pid 23748:tid 140054219437824] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 5 in daemon process 'api'.
[Wed Nov 04 11:17:04.613019 2020] [wsgi:debug] [pid 23748:tid 140054244615936] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 2 in daemon process 'api'.
[Wed Nov 04 11:17:04.613024 2020] [wsgi:debug] [pid 23748:tid 140054236223232] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 3 in daemon process 'api'.
[Wed Nov 04 11:17:04.613130 2020] [wsgi:debug] [pid 23748:tid 140054194259712] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 8 in daemon process 'api'.
[Wed Nov 04 11:17:04.613191 2020] [wsgi:debug] [pid 23748:tid 140054185867008] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 9 in daemon process 'api'.
[Wed Nov 04 11:17:04.613198 2020] [wsgi:debug] [pid 23748:tid 140054177474304] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 10 in daemon process 'api'.
[Wed Nov 04 11:17:04.613230 2020] [wsgi:debug] [pid 23748:tid 140054211045120] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 6 in daemon process 'api'.
[Wed Nov 04 11:17:04.613235 2020] [wsgi:debug] [pid 23748:tid 140054169081600] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 11 in daemon process 'api'.
[Wed Nov 04 11:17:04.613239 2020] [wsgi:debug] [pid 23748:tid 140054202652416] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 7 in daemon process 'api'.
[Wed Nov 04 11:17:04.613258 2020] [wsgi:debug] [pid 23748:tid 140054160688896] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 12 in daemon process 'api'.
[Wed Nov 04 11:17:04.613312 2020] [wsgi:debug] [pid 23748:tid 140054143903488] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 14 in daemon process 'api'.
[Wed Nov 04 11:17:04.613326 2020] [wsgi:debug] [pid 23748:tid 140054152296192] src/server/mod_wsgi.c(9118): mod_wsgi (pid=23748): Started thread 13 in daemon process 'api'.

```

**Comment by andrewgodwin** [comment]
This isn't a problem with `asgiref` - your system Python is broken. Graham comments more to this effect on the ticket you linked.
