### ISSUE TITLE
v3.4.0 get_running_loop break django-channels runworker

### ISSUE THREAD

**Issue by lsaavedr** [django/asgiref#278]
get_running_loop raise RuntimeError with any django-channels runworker command because there is no running event loop... 

patch?
```diff
diff --git a/asgiref/server.py b/asgiref/server.py
index fb1c394..7f32734 100644
--- a/asgiref/server.py
+++ b/asgiref/server.py
@@ -56,7 +56,7 @@ class StatelessServer:
         """
         Runs the asyncio event loop with our handler loop.
         """
-        event_loop = get_running_loop()
+        event_loop = asyncio.get_event_loop()
         asyncio.ensure_future(self.application_checker())
         try:
             event_loop.run_until_complete(self.handle())
```

**Comment by andrewgodwin** [comment]
What version of Python are you running on? The code you suggest is deprecated in 3.10, which is why we moved to `get_running_loop` in the most recent release.

**Comment by lsaavedr** [comment]
3.8.5, but with all python version there is no running event loop (with django-channels runworker), and then get_running_loop raise RuntimeError

**Comment by carltongibson** [comment]
This looks like a duplicate of https://github.com/django/channels/issues/1713 — where there is a minimal reproduce project provided.

**Comment by bj00rn** [comment]
I have the same problem in https://github.com/django/channels/issues/1713.

Tested with python 3.8.4 and python 3.10.0 (3.10.0a5)

no problems when `asgiref==3.3.4` is installed

**Comment by tsantor** [comment]
I have the same problem in [django/channels#1713](https://github.com/django/channels/issues/1713) as well.

`docker-compose -f local.yml run --rm django python manage.py runworker game_engine`

```
Running worker for channels ['game_engine']
[2021-07-01 22:00:29,442 INFO/Process-1] [runworker] Running worker for channels ['game_engine']
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/channels/management/commands/runworker.py", line 46, in handle
    worker.run()
  File "/usr/local/lib/python3.8/site-packages/asgiref/server.py", line 59, in run
    event_loop = get_running_loop()
RuntimeError: no running event loop
make: *** [fom_engine] Error 1
```

```
asgiref==3.4.1
channels==3.0.3
channels-redis==3.2.0
daphne==3.0.1
django==3.0.11
```

Debian GNU/Linux 10 (buster), Python 3.8.4

As @bj00rn  suggested, I have no problems when `asgiref==3.3.4` is installed.

**Comment by andrewgodwin** [comment]
Curious. Looks like part of Channels was relying on this working when an event loop wasn't actually running but still present in the thread.

I'll leave this open in case we find out the issue is in the ASGI side - @carltongibson. let me know if you want my help digging into this.

**Comment by lsaavedr** [comment]
the channel runworker is a class with parent class StatelessServer, this bug is raised when StatelessServer.run() function is apply

**Comment by carltongibson** [comment]
>… let me know if you want my help digging into this.

Thanks @andrewgodwin — just time 🥳 — so if you have spare of that then super. 

Anyone else if welcome to investigate too(!) 

Otherwise, I’m back on active duty for channels, so to speak, so I’m happy to pick it up.

**Comment by carltongibson** [comment]
> the channel runworker is a class with parent class StatelessServer, this bug is raised when StatelessServer.run() function is apply

Right, yes, so this is the issue (as far as I can see). 

`StatelessServer.run()` is the top-level sync entry point for kicking off the async `handle()` method.

https://github.com/django/asgiref/blob/c9d6d1ae742307e03d1072630c030123e0c2ad99/asgiref/server.py#L55-L64

83d482340b2be2ba5bb5914dce85e260d05319ae switched to `get_running_loop()` but that doesn't make sense in this context. 

Could we just use `asyncio.run()` here? 🤔

**Comment by lsaavedr** [comment]
there exist two problems:
  - lack of definition on how to run a StatelessServer in async and sync scenery
  - lack of test that run process
with that points this bug would not exist 🥺, I dont know how implement that points 🥺🥺🥺

**Comment by andrewgodwin** [comment]
@carltongibson If you don't care about Python 3.6 I believe `asyncio.run` would be a reasonable thing to use. I also believe you might just be able to wrap `handle()` in `async_to_sync`, and achieve the same effect?

**Comment by carltongibson** [comment]
@andrewgodwin right... yes... good point. That had slipped my mind. 

I think given that 83d482340b2be2ba5bb5914dce85e260d05319ae tried to maintain Python 3.6 compatibility, and then Channels still supports that (for now at least 🙂) `async_to_sync` route is likely better. 

I'll play over the weekend…

@lsaavedr open to ideas but this kind of top-level command is not that open to testing… (_How do we test, say `runserver`?_)

**Comment by fabthegreat** [comment]
Still no running loop for me:
Django-4.0.2 asgiref-3.5.0 channels-3.0.4

just writing a raw asyncio.get_running_loop() in my consumer...
