### ISSUE TITLE
Installing pre-commit hooks for asgiref causes a (confusing!) "poetry" related error

### ISSUE THREAD

**Issue by LucidDan** [django/asgiref#372]
I've been doing some work on a typing PR for asgiref, and ran into a problem installing pre-commit hooks:

```
(asgiref) ➜  asgiref git:(main) ✗ pre-commit install-hooks
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/dans/.cache/pre-commit/repoon7vdpun/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/dans/.cache/pre-commit/repoon7vdpun
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/Users/dans/.cache/pre-commit/repoon7vdpun/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/dans/.cache/pre-commit/repoon7vdpun/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/dans/.cache/pre-commit/repoon7vdpun/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/65/8vp4vwdn56df9zt7y0x2w6d40000gn/T/pip-build-env-s3yam3e1/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/65/8vp4vwdn56df9zt7y0x2w6d40000gn/T/pip-build-env-s3yam3e1/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /Users/dans/.cache/pre-commit/pre-commit.log
```

This appears to be due to https://github.com/PyCQA/isort/issues/2083
Updating to isort 5.11.5 for pre-commit resolves it.
Side note; looks like isort 5.12.0 or later should not be updated to until python 3.7 support is dropped, although I guess few people are using 3.7 to do development work, so maybe it's not a big deal...regardless, I figured I'd keep the change to a minimum.

A tiny PR in #371 updates the pre-commit configuration.

**Comment by andrewgodwin** [comment]
I think we'll drop 3.7 at its EOL in 4 months, but thanks for the PR to fix it!
