### ISSUE TITLE
Incompatibility with asgiref, pypy and coverage

### ISSUE THREAD

**Issue by LilyAcorn** [django/asgiref#393]
I'm not sure which project is at fault, but asgiref `3.7.0` and `3.7.1` both fail. `3.6.0` does not.

If I put this in a `test.py`:
```python
from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
```

And run:

```
$ coverage run test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
  File "/home/ian/work/asgiref/asgiref/sync.py", line 130, in <module>
    class AsyncToSync(Generic[_P, _R]):
  File "/home/ian/.pyenv/versions/pypy3.8-7.3.11/lib/pypy3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/home/ian/.pyenv/versions/pypy3.8-7.3.11/lib/pypy3.8/typing.py", line 890, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Generic[...] must all be type variables
```

These are my installed packages:

```
$ pip freeze
asgiref==3.7.1
cffi==1.15.1
coverage==7.2.6
greenlet==0.4.13
hpy==0.0.4.dev179+g9b5d200
readline==6.2.4.1
typing_extensions==4.6.1
```

Bisected to 72f45c5feb158f71c5b5fb337e323c7bacd6c7b3 locally.

**Comment by LilyFoote** [comment]
Actually this might be a coverage bug, since this only appears when I run under coverage.

**Comment by andrewgodwin** [comment]
This bug looks very like #392 - are you sure that coverage is not running in a separate virtualenv or similar with an old typing_extensions package?

**Comment by andrewgodwin** [comment]
Hmm, this is perplexing. It's possible it's `pypy` instead - are you able to try on cpython?

**Comment by LilyFoote** [comment]
I can confirm I don't see the error on cpython 3.9.13.

**Comment by andrewgodwin** [comment]
OK, so this must be some sort of pypy typing incompatability. Have you tried pypy3.9?

I'm not sure if we have a sensible way to fix this other than saying "stick to asgiref 3.6 if you're on pypy" - the only real improvements in 3.7 were some speed optimisations and typing changes. I've just also relased 3.7.2, which changes the type signatures again, but I don't think pypy will be happy with it still, as it's still some weird ParamSpec stuff.

**Comment by jpmckinney** [comment]
I've tried pypy3.9 and it's the same error (`TypeError: Parameters to Generic[...] must all be type variables`).

Using asgiref 3.6 instead of 3.7 works.

**Comment by andrewgodwin** [comment]
I suspect we'll just have to say that pypy is incompatible with the typing in asgiref 3.7 for now then, which is annoying. I'll investigate and see if we can find some way to replace Generic with something that ignores errors if pypy is detected, but I suspect the only real fix here will be pypy hitting 3.10 and proper ParamSpec support.

**Comment by jpmckinney** [comment]
> I suspect the only real fix here will be pypy hitting 3.10 and proper ParamSpec support.

pypy 3.10 was released June 16, 2023 https://doc.pypy.org/en/latest/release-v7.3.12.html

**Comment by carltongibson** [comment]
@jpmckinney @LilyAcorn Could I ask you to confirm if this is resolved or not? Thanks.
